version: '3.4'

services:
  message_bus:
    image: rabbitmq:3-management-alpine
    container_name: 'message_bus_rabbitmq'
  rft.aggregation.api:
    image: ${DOCKER_REGISTRY-}rftaggregationapi
    build:
      context: .
      dockerfile: RFT.Aggregation.Api/Dockerfile